### PR TITLE
Update the version number in package.json and chrome/manifest.json

### PR DESCRIPTION
**Pull request by isyuricunha**
+ Fix run out memory - if you haver more than 200 matches, it don't crash anymore
+ Update the changelog in README.md
+ Put the new version number in the commit message
+ Put colors
+ Put the new version number in the tag
+ Add check for don't double message
+ Add log for don't double message
+ Fix run out memory

### CODE REVIEW

**Comment by isyuricunha** [comment]
Hi @Geczy ,

If it is possible, add me in this project, for edit.

I really like to continue this project.

Kind regards,
Yuri.

**Comment by isyuricunha** [comment]
[update version package.json/chrome/manifest 3.0.2](https://github.com/isyuricunha/tinder-autopilot/commit/6dd00374a0c6b0f1b3ea06e303063b3947b1b23b)

**Comment by Geczy** [comment]
very cool, thanks for the contribution!! by the way, version numbers don't have to be adjusted. the script does it for us by running any of these:

```
    "major": "dotenv release-it -- major --ci",
    "minor": "dotenv release-it -- minor --ci",
    "patch": "dotenv release-it -- patch --ci",
```

**Comment by isyuricunha** [comment]
Hi,

Okay. I hadn't realized that. Thank you.

**Pull request merged**
